
# The log file location
log:
filename: "spero.log"

# All the databases used by the system
databases:
  dev: "data/spero.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Refugees
    - Employers
    - Asylums
    - Jobs



users:
  refugee: "scottj"
  employer: "davood"
